[package]
name = "rmf_crowdsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
rand = "0.8.5"
statrs = "0.15.0"
